-- Generated by lampe

import «sha256-0.0.0».Extracted.GeneratedTypes
import Lampe

open Lampe

noir_global_def «sha256-0.0.0»::sha256::constants::BLOCK_SIZE: u32 = (64: u32);

noir_global_def «sha256-0.0.0»::sha256::constants::MSG_SIZE_PTR: u32 = (56: u32);

noir_global_def «sha256-0.0.0»::sha256::constants::INT_BLOCK_SIZE: u32 = (16: u32);

noir_global_def «sha256-0.0.0»::sha256::constants::INT_SIZE: u32 = (4: u32);

noir_global_def «sha256-0.0.0»::sha256::constants::INT_SIZE_PTR: u32 = (#_uDiv returning u32)((«sha256-0.0.0»::sha256::constants::MSG_SIZE_PTR<> as λ() -> u32)(), («sha256-0.0.0»::sha256::constants::INT_SIZE<> as λ() -> u32)());

noir_global_def «sha256-0.0.0»::sha256::constants::TWO_POW_8: u32 = (256: u32);

noir_global_def «sha256-0.0.0»::sha256::constants::TWO_POW_16: u32 = (#_uMul returning u32)((«sha256-0.0.0»::sha256::constants::TWO_POW_8<> as λ() -> u32)(), (256: u32));

noir_global_def «sha256-0.0.0»::sha256::constants::TWO_POW_24: u32 = (#_uMul returning u32)((«sha256-0.0.0»::sha256::constants::TWO_POW_16<> as λ() -> u32)(), (256: u32));

noir_global_def «sha256-0.0.0»::sha256::constants::TWO_POW_32: Field = (#_fMul returning Field)((#_cast returning Field)((«sha256-0.0.0»::sha256::constants::TWO_POW_24<> as λ() -> u32)()), (256: Field));

noir_global_def «sha256-0.0.0»::sha256::constants::INITIAL_STATE: @«sha256-0.0.0»::sha256::constants::STATE<> = (#_mkArray returning Array<u32, 8: u32>)((1779033703: u32), (3144134277: u32), (1013904242: u32), (2773480762: u32), (1359893119: u32), (2600822924: u32), (528734635: u32), (1541459225: u32));

def «sha256-0.0.0».Sha256.Constants.env : Env := Env.mk
  [«sha256-0.0.0::sha256::constants::BLOCK_SIZE», «sha256-0.0.0::sha256::constants::MSG_SIZE_PTR», «sha256-0.0.0::sha256::constants::INT_BLOCK_SIZE», «sha256-0.0.0::sha256::constants::INT_SIZE», «sha256-0.0.0::sha256::constants::INT_SIZE_PTR», «sha256-0.0.0::sha256::constants::TWO_POW_8», «sha256-0.0.0::sha256::constants::TWO_POW_16», «sha256-0.0.0::sha256::constants::TWO_POW_24», «sha256-0.0.0::sha256::constants::TWO_POW_32», «sha256-0.0.0::sha256::constants::INITIAL_STATE»]
  []
