-- Generated by lampe

import «sha256-0.0.0».Extracted.GeneratedTypes
import Lampe

open Lampe

noir_def «sha256-0.0.0»::sha256::oracle_tests::sha256_hash_oracle<>(input: Vector<u8>) -> Array<u8, 32: u32> := {
  (#_fresh returning Array<u8, 32: u32>)()
}

noir_def «sha256-0.0.0»::sha256::oracle_tests::get_sha256_hash<>(input: Vector<u8>) -> Array<u8, 32: u32> := {
  (#_fresh returning Array<u8, 32: u32>)()
}

noir_def «sha256-0.0.0»::sha256::oracle_tests::test_sha256_1<>(input: Array<u8, 1: u32>) -> Unit := {
  (#_fresh returning Unit)()
}

noir_def «sha256-0.0.0»::sha256::oracle_tests::test_sha256_63<>(input: Array<u8, 63: u32>) -> Unit := {
  (#_fresh returning Unit)()
}

noir_def «sha256-0.0.0»::sha256::oracle_tests::test_sha256_511<>(input: Array<u8, 511: u32>) -> Unit := {
  (#_fresh returning Unit)()
}

noir_def «sha256-0.0.0»::sha256::oracle_tests::test_sha256_512<>(input: Array<u8, 512: u32>) -> Unit := {
  (#_fresh returning Unit)()
}

def «sha256-0.0.0».Sha256.OracleTests.env : Env := Env.mk
  [«sha256-0.0.0::sha256::oracle_tests::sha256_hash_oracle», «sha256-0.0.0::sha256::oracle_tests::get_sha256_hash», «sha256-0.0.0::sha256::oracle_tests::test_sha256_1», «sha256-0.0.0::sha256::oracle_tests::test_sha256_63», «sha256-0.0.0::sha256::oracle_tests::test_sha256_511», «sha256-0.0.0::sha256::oracle_tests::test_sha256_512»]
  []
