-- Generated by lampe

import «std-1.0.0-beta.14».Extracted.GeneratedTypes
import Lampe

open Lampe

noir_type_alias «sha256-0.0.0»::sha256::constants::BLOCK_BYTE_PTR<> := u32;

noir_type_alias «sha256-0.0.0»::sha256::constants::INT_BLOCK<> := Array<u32, 16: u32>;

noir_type_alias «sha256-0.0.0»::sha256::constants::HASH<> := Array<u8, 32: u32>;

noir_type_alias «sha256-0.0.0»::sha256::constants::MSG_BLOCK<> := @«sha256-0.0.0»::sha256::constants::INT_BLOCK<>;

noir_type_alias «sha256-0.0.0»::sha224::constants::HASH_SHA224<> := Array<u8, 28: u32>;

noir_type_alias «sha256-0.0.0»::sha256::constants::STATE<> := Array<u32, 8: u32>;

