-- Generated by lampe

import «sha256-0.0.0».Extracted.GeneratedTypes
import Lampe

open Lampe

noir_global_def «sha256-0.0.0»::sha224::constants::INITIAL_STATE_SHA224: @«sha256-0.0.0»::sha256::constants::STATE<> = (#_mkArray returning Array<u32, 8: u32>)((3238371032: u32), (914150663: u32), (812702999: u32), (4144912697: u32), (4290775857: u32), (1750603025: u32), (1694076839: u32), (3204075428: u32));

def «sha256-0.0.0».Sha224.Constants.env : Env := Env.mk
  [«sha256-0.0.0::sha224::constants::INITIAL_STATE_SHA224»]
  []
